preserve_hierarchy: true
pull_request_title: 'docs(i18n): sync i18n files from Crowdin'
commit_message: 'docs(i18n): sync translation %original_file_name% for %language%'
files:
  - source: /**/*.tsx?
    translation: /**/*.%locale%.tsx
    update_option: 'update_as_unapproved'
    skip_untranslated_strings: true
