export enum RouteKeys {
  Home = '/',
  BoxList = '/list',
  Details = '/details',
  DetailsTokenTab = '/details/token',
  DetailsDescTab = '/details/desc/:index',
  Edit = '/edit',
  EditDescription = '/edit/desc',
  EditMeta = '/edit/meta',
  Faqs = '/faqs',
  Profile = '/profile',
  ProfileMaskboxCollections = '/profile/maskbox',
  ProfileOtherCollections = '/profile/others',
  MyMaskboxes = '/my-maskboxes',
}
