name: Github Pages

on:
  push:
  workflow_dispatch:
    inputs:
      ignore_on_mainnet:
        description: 'Ignore ids on Mainnet'
        default: '12,14'
        require: false
        type: string

      ignore_on_matic:
        description: 'Ignore ids on matic'
        default: ''
        require: false
        type: string

      ignore_on_bsc:
        description: 'Ignore ids on bsc'
        default: ''
        require: false
        type: string

      ignore_on_rinkeby:
        description: 'Ignore ids on rinkeby'
        default: ''
        require: false
        type: string

jobs:
  deploy:
    name: Depoly
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: |
          IGNORE_IDS_ON_MAINNET=${{ inputs.ignore_on_mainnet }}
          IGNORE_IDS_ON_MATIC=${{ inputs.ignore_on_matic }}
          IGNORE_IDS_ON_BSC=${{ inputs.ignore_on_bsc }}
          IGNORE_IDS_ON_RINKEBY=${{ inputs.ignore_on_rinkeby }}
          pnpm build
          cp public/CNAME dist
          cp public/logo.png dist
        env:
          INFURA_ID: d65858b010d249419cf8687eca12b094,d74bd8586b9e44449cef131d39ceeefb
          COMMIT: ${{ github.sha }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
