name: Github Pages

on:
  push:

jobs:
  deploy:
    name: Depoly
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: |
          pnpm build
          cp public/CNAME dist
          cp public/logo.png dist
        env:
          INFURA_ID: d65858b010d249419cf8687eca12b094,d74bd8586b9e44449cef131d39ceeefb
          COMMIT: ${{ github.sha }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
