name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Depoly
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install
        run: yarn install

      - name: Build
        run: |
          yarn build
          cp public/CNAME dist
          cp public/logo.png dist
        env:
          INFURA_ID: d74bd8586b9e44449cef131d39ceeefb

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
